language: csharp

mono:
- 3.12.0

install:
- cd /usr/local/src
- sudo git clone --depth=10 --branch=master https://github.com/chocolatey/choco.git
- cd /usr/local/src/choco
- sudo chmod +x build.sh
- sudo ./build.sh
- sudo apt-get install tree
- tree
- sudo cp choco /usr/local/bin/choco
- sudo chmod +x /usr/local/bin/choco

script:
- echo "ok."