version: b{build}
branches:
  only:
    - master
environment:
  CHOCO_API:
    secure: 39O7NZuAa8JRWGMtXGEPkNzLTqgqYL7Ssq5Blms1J6oEaXJ3Yn+zpw1Y1S8KjH9t

build_script:
  - ps: .\repack.ps1

test_script:
  - ps: .\test_installation.ps1

deploy_script:
  - ps: .\deploy.ps1