version: 3.7.5.{build}
branches:
  only:
    - test_ci
environment:
  TOKEN:
    secure: TihxnYdIwtxnhS568XO7PECa6ETPBcTk2fUSgO8wq60c75Io9xPXE3TtLCBf5D6h

install:
  - cinst autohotkey

build_script:
  - cmd: >-
      cd "C:\projects\chocolatey-packages"
      .\update_packages.ahk

deploy_script:
  - ps: >-
      Write-Host $env:APPVEYOR_REPO_TAG ;
      if($env:APPVEYOR_REPO_BRANCH -eq 'master' -And $env:APPVEYOR_REPO_TAG -eq 'true') {
        $version = $env:APPVEYOR_BUILD_VERSION -replace('\.[^.\\/]+$') ;
        $version = $version -replace('-ce') ;
        echo "It works."
      }